### ISSUE TITLE
A switch to show/hide certain types of elements

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/meix.js#55]
For example, a public function that allows to show or hide all the zones of staff lines.

**Comment by ahwitz** [comment]
Two questions:

-Should this just be XML tag names (<neume ...>, <sb ...>), or do you want more specification than just that?

-Should this be on the user to choose what they want to show/hide or should it be on either the user or the developer? (person in your position)

**Comment by lingxiaoyang** [comment]
For this case, XML tag names are enough.

Primarily it's for users. But of course, it would be really nice to have a public function to developers.

**Comment by ahwitz** [comment]
I phrased that question the wrong way, was supposed to be (developers) or (users and developers) - I'll implement it as a public-facing function but with a toolbar interface too.
