### ISSUE TITLE
Allow editing the attributes of a highlighted XML tag

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/meix.js#58]
For example, I would like to modify the attribute `n` of a `<sb>` tag, but once I hit backspace or delete while the cursor is on that line, the entire `<sb>` element is removed.

**Comment by ahwitz** [comment]
What commit are you on?

**Comment by lingxiaoyang** [comment]
I'm on the latest commit of master.

**Comment by ahwitz** [comment]
roger. gimme a day or two
