### ISSUE TITLE
Cannot type space in editor

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/meix.js#60]
The editor doesn't insert a space when pressing space bar. Copying and pasting a space works.

**Comment by ahwitz** [comment]
@lingxiaoyang / @ribu - can either of you verify this was fixed and we just didn't close the issue? I'm pretty sure this was what I solved a while ago but I'm not sure.

**Comment by ahankinson** [comment]
Seems to me that this one's pretty easy to check. I can confirm that pressing the space bar inserts a space in the Verovio editor. Does that address it?

**Comment by ahwitz** [comment]
Because Ling-Xiao reported this, I wanted to make sure there wasn't a specific case he found that this happened in that is still unsolved.
